import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';

import { Role } from '../../common/enums/role.enum';
import { isUniqueViolationError } from '../../common/utils/postgres-error.util';
import { AuditLogWriterService } from '../audit/audit-log-writer.service';
import type { AuthenticatedUser } from '../auth/interfaces/authenticated-user.interface';
import { ProcessVersionsRepository } from '../process_versions/process-versions.repository';
import { WorkflowAuthorizationService } from '../workflow_support/workflow-authorization.service';
import type { CreateProcedureDto } from './dto/create-procedure.dto';
import type { UpdateProcedureDto } from './dto/update-procedure.dto';
import type { ProcedureActivityDto } from './dto/shared-procedure.dto';
import type { ProcedureRecord } from './procedures.repository';
import { ProceduresRepository } from './procedures.repository';

@Injectable()
export class ProceduresService {
  private static readonly DUPLICATE_CODE_MESSAGE =
    'A Procedure with the same code already exists for this version';

  constructor(
    private readonly proceduresRepository: ProceduresRepository,
    private readonly processVersionsRepository: ProcessVersionsRepository,
    private readonly workflowAuthorizationService: WorkflowAuthorizationService,
    private readonly auditLogWriterService: AuditLogWriterService,
  ) {}

  async create(
    processVersionId: string,
    createProcedureDto: CreateProcedureDto,
    currentUser: AuthenticatedUser,
  ): Promise<ProcedureRecord> {
    this.assertEditorRole(currentUser);
    const processVersion = await this.getRequiredVersion(processVersionId);

    await this.workflowAuthorizationService.assertSameTeamAsProcessVersionOwner(
      processVersionId,
      currentUser,
    );
    this.ensureDraftLifecycle(processVersion.lifecycleState);
    this.ensureCompleteProcedurePayload(createProcedureDto);
    const nextProcedureCode =
      await this.proceduresRepository.getNextProcedureCode(processVersionId);

    try {
      const procedure = await this.proceduresRepository.create({
        processVersionId,
        code: nextProcedureCode,
        title: createProcedureDto.title,
        utility: createProcedureDto.utility,
        warranty: createProcedureDto.warranty,
        outcome: createProcedureDto.outcome,
        policy: createProcedureDto.policy,
        activities: this.mapActivities(createProcedureDto.activities),
        inputs: createProcedureDto.inputs,
        outputs: createProcedureDto.outputs,
        actorId: currentUser.id,
      });

      await this.auditLogWriterService.create({
        entityType: 'procedure',
        entityId: procedure.id,
        action: 'CREATE',
        actorId: currentUser.id,
        reasonForChange: 'Created procedure via API',
        newData: procedure,
      });

      return procedure;
    } catch (error: unknown) {
      if (isUniqueViolationError(error)) {
        throw new ConflictException(ProceduresService.DUPLICATE_CODE_MESSAGE);
      }

      throw error;
    }
  }

  async listByProcessVersionId(
    processVersionId: string,
    currentUser: AuthenticatedUser,
  ): Promise<ProcedureRecord[]> {
    this.assertBackofficeContentRole(currentUser);
    await this.getRequiredVersion(processVersionId);

    return await this.proceduresRepository.findByProcessVersionId(
      processVersionId,
    );
  }

  async listAll(currentUser: AuthenticatedUser): Promise<ProcedureRecord[]> {
    this.assertBackofficeContentRole(currentUser);
    return await this.proceduresRepository.findAllForBackoffice();
  }

  async getById(
    id: string,
    currentUser: AuthenticatedUser,
  ): Promise<ProcedureRecord> {
    this.assertBackofficeContentRole(currentUser);
    const procedure = await this.proceduresRepository.findById(id);

    if (!procedure) {
      throw new NotFoundException('Procedure not found');
    }

    return procedure;
  }

  async update(
    id: string,
    updateProcedureDto: UpdateProcedureDto,
    currentUser: AuthenticatedUser,
  ): Promise<ProcedureRecord> {
    this.assertEditorRole(currentUser);
    const currentProcedure = await this.getById(id, currentUser);
    const processVersion = await this.getRequiredVersion(
      currentProcedure.processVersionId,
    );
    const rawUpdateProcedureDto = updateProcedureDto as UpdateProcedureDto & {
      code?: unknown;
    };

    await this.workflowAuthorizationService.assertSameTeamAsProcedureOwner(
      id,
      currentUser,
    );
    this.ensureDraftLifecycle(processVersion.lifecycleState);

    if ('code' in rawUpdateProcedureDto) {
      throw new BadRequestException(
        'Procedure code is generated by the backend and cannot be changed',
      );
    }

    this.ensureCompleteProcedurePayload(updateProcedureDto);

    try {
      const updatedProcedure = await this.proceduresRepository.update(
        id,
        {
          title: updateProcedureDto.title,
          utility: updateProcedureDto.utility,
          warranty: updateProcedureDto.warranty,
          outcome: updateProcedureDto.outcome,
          policy: updateProcedureDto.policy,
          activities: updateProcedureDto.activities
            ? this.mapActivities(updateProcedureDto.activities)
            : undefined,
          inputs: updateProcedureDto.inputs,
          outputs: updateProcedureDto.outputs,
        },
        currentUser.id,
      );

      await this.auditLogWriterService.create({
        entityType: 'procedure',
        entityId: updatedProcedure.id,
        action: 'UPDATE',
        actorId: currentUser.id,
        reasonForChange: 'Updated procedure via API',
        oldData: currentProcedure,
        newData: updatedProcedure,
      });

      return updatedProcedure;
    } catch (error: unknown) {
      if (isUniqueViolationError(error)) {
        throw new ConflictException(ProceduresService.DUPLICATE_CODE_MESSAGE);
      }

      throw error;
    }
  }

  async delete(id: string, currentUser: AuthenticatedUser): Promise<void> {
    this.assertEditorRole(currentUser);
    const procedure = await this.getById(id, currentUser);
    const processVersion = await this.getRequiredVersion(
      procedure.processVersionId,
    );

    await this.workflowAuthorizationService.assertSameTeamAsProcedureOwner(
      id,
      currentUser,
    );
    this.ensureDraftLifecycle(processVersion.lifecycleState);

    if (procedure.code) {
      throw new ConflictException(
        'Cannot delete procedure with a generated code. To maintain code continuity, procedures with codes cannot be deleted.',
      );
    }

    await this.proceduresRepository.delete(id);
    await this.auditLogWriterService.create({
      entityType: 'procedure',
      entityId: procedure.id,
      action: 'DELETE',
      actorId: currentUser.id,
      reasonForChange: 'Deleted procedure via API',
      oldData: procedure,
    });
  }

  private async getRequiredVersion(processVersionId: string) {
    const processVersion =
      await this.processVersionsRepository.findById(processVersionId);

    if (!processVersion) {
      throw new NotFoundException('Process version not found');
    }

    return processVersion;
  }

  private ensureDraftLifecycle(lifecycleState: string): void {
    if (lifecycleState !== 'Draft') {
      throw new ConflictException(
        'Procedures can only be modified for Draft versions',
      );
    }
  }

  private mapActivities(
    activities: ProcedureActivityDto[],
  ): Record<string, unknown>[] {
    return activities.map((activity) => ({
      resource: activity.resource,
      service_action: activity.serviceAction,
      work_instruction: activity.workInstruction,
    }));
  }

  private ensureCompleteProcedurePayload(
    procedure: UpdateProcedureDto | CreateProcedureDto,
  ): void {
    if (
      procedure.title.trim() === '' ||
      procedure.utility.trim() === '' ||
      procedure.warranty.trim() === '' ||
      procedure.outcome.trim() === '' ||
      procedure.policy.trim() === '' ||
      procedure.activities.length === 0 ||
      procedure.inputs.length === 0 ||
      procedure.outputs.length === 0
    ) {
      throw new BadRequestException(
        'All procedure fields are required, including at least one activity, input, and output',
      );
    }
  }

  private assertEditorRole(currentUser: AuthenticatedUser): void {
    if (currentUser.role !== Role.EDITOR) {
      throw new ForbiddenException('Only editors can manage procedures');
    }
  }

  private assertBackofficeContentRole(currentUser: AuthenticatedUser): void {
    if (
      ![Role.EDITOR, Role.REVIEWER, Role.PUBLISHER, Role.VIEWER].includes(
        currentUser.role,
      )
    ) {
      throw new ForbiddenException('Only content roles can access procedures');
    }
  }
}
